### ISSUE TITLE
使用rollup打包时报错

### ISSUE THREAD

**Issue by LancerSung** [SuperMap/iClient-JavaScript#47]
### Request a feature or report a bug? [这是一个需求还是一个缺陷]
缺陷
### One-line summary [问题简述]
- yarn add @supermap/iclient-leaflet
- 编写业务代码`export { tiledMapLayer } from '@supermap/iclient-leaflet';`
- 使用rollup打包
控制台报错，打包不成功，错误信息如下
```
!] (plugin buble) SyntaxError: Unexpected token (2:8)
node_modules/proj4/package.json (2:8)
1 : {
2 :   "name": "proj4",
            ^
SyntaxError: Unexpected token (2:8)
    at Object.pp$4.raise (/Users/node_modules/acorn/dist/acorn.js:2825:15)
    at Object.pp.unexpected (/Users//node_modules/acorn/dist/acorn.js:689:10)
    at Object.pp.semicolon (/Users//node_modules/acorn/dist/acorn.js:666:66)
    at Object.pp$1.parseExpressionStatement (/Users/node_modules/acorn/dist/acorn.js:1145:10)
    at Object.pp$1.parseStatement (/Users//node_modules/acorn/dist/acorn.js:880:26)
    at Object.parseStatement (/Users/node_modules/acorn-dynamic-import/lib/index.js:63:118)
    at Object.pp$1.parseBlock (/Users/node_modules/acorn/dist/acorn.js:1161:23)
    at Object.pp$1.parseStatement (/Users//acorn/dist/acorn.js:845:36)
    at Object.parseStatement (/Users//node_modules/acorn-dynamic-import/lib/index.js:63:118)
    at Object.pp$1.parseTopLevel (/Users//node_modules/acorn/dist/acorn.js:746:23)
    at Object.parse (/Users//node_modules/acorn/dist/acorn.js:553:17)
    at Function.parse (/Users//node_modules/acorn/dist/acorn.js:576:37)
    at Object.transform (/Users//node_modules/buble/dist/buble.cjs.js:4343:16)
    at Object.transform (/Users//node_modules/rollup-plugin-buble/dist/rollup-plugin-buble.cjs.js:20:18)
    at Promise.resolve.then (/Users//node_modules/rollup/dist/rollup.js:16026:25)
```
### Version [产品及版本]
+ iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]:
for leaflet
+ iClient version [iClient 版本]:
^10.0.0-beta
+ Browser version [浏览器类型和版本]:
na
+ OS Version [操作系统类型和版本]:
macos
+ rollup版本
1.21.2
+ rollup-plugin-buble版本
0.19.8
----------

### Actual Behavior [当前现象]
rollup打包报错
### Expected Behavior [期望现象]
rollup正常打包
### Example of reproducing the issue [重现现象的例子]

----------

**Comment by songyumeng** [comment]
谢谢您提的issue
最新版本@supermap/iclient-leaflet@10.1.0是否仍有此问题。
若仍有问题请提供更详细的rollup配置信息，谢谢。
